using ReScene.App.Core.Helpers;

namespace ReScene.App.Core.Tests;

public class FormatUtilitiesTests
{
    [Fact]
    public void NormalizeAppName_AutoGeneratedValue_RefreshesToLiveDefault()
    {
        string stale = "ReScene Manager v2.0.0 (92f6e9f)";
        string result = FormatUtilities.NormalizeAppName(stale);
        Assert.Equal(FormatUtilities.GetDefaultAppName(), result);
        Assert.NotEqual(stale, result);
    }

    [Theory]
    [InlineData("ReScene.NET v1.5.0 (92f6e9f)")] // WPF-era settings
    [InlineData("ReScene.NET v2.0.0 (ac54e51)")] // v2.0.0 still stamped the legacy name
    public void NormalizeAppName_LegacyAutoGeneratedValue_StillRefreshes(string stale)
    {
        string result = FormatUtilities.NormalizeAppName(stale);
        Assert.Equal(FormatUtilities.GetDefaultAppName(), result);
        Assert.NotEqual(stale, result);
    }

    [Fact]
    public void GetDefaultAppName_StampsTheRebrandedName()
        => Assert.StartsWith("ReScene Manager", FormatUtilities.GetDefaultAppName(), StringComparison.Ordinal);

    [Fact]
    public void NormalizeAppName_Blank_ReturnsLiveDefault()
    {
        Assert.Equal(FormatUtilities.GetDefaultAppName(), FormatUtilities.NormalizeAppName(""));
        Assert.Equal(FormatUtilities.GetDefaultAppName(), FormatUtilities.NormalizeAppName(null));
        Assert.Equal(FormatUtilities.GetDefaultAppName(), FormatUtilities.NormalizeAppName("   "));
    }

    [Fact]
    public void NormalizeAppName_CustomValue_IsUnchanged() => Assert.Equal("MyGroup", FormatUtilities.NormalizeAppName("MyGroup"));
}
